gem 'minitest', '~> 5.2'
# # require 'simplecov'; SimpleCov.start
require 'minitest/autorun'
require 'minitest/pride'
#
# # require_relative 'customer_repository_test.rb'
# # require_relative 'item_test.rb'
# # require_relative 'customer_test.rb'
# # require_relative 'merchant_repository_test.rb'
# # require_relative 'merchant_test.rb'
# # require_relative 'invoice_item_repository_test.rb'
# # require_relative 'parser_test.rb'
# # require_relative 'invoice_item_test.rb'
# # require_relative 'sales_engine_test.rb'
# # require_relative 'invoice_repository_test.rb'
# # require_relative 'test_helper.rb'
# # require_relative 'invoice_test.rb'
# # require_relative 'parser_test.rb'
# # require_relative 'transaction_repository_test.rb'
# # require_relative 'item_repository_test.rb'
# # require_relative 'transaction_test.rb'
